apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rstest
  labels:
    rs: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      containers:
      - name: max
        image: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: max
spec:
  type: NodePort      
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
