apiVersion: v1
kind: ReplicationController
metadata:
  name: max
spec:
  replicas: 3
  selector: 
    app: max
  template:
    metadata:
      labels:
        app: max
    spec:
      containers:
      - name: test
        image: nginx
        ports:
        - containerPort: 80          
