apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-ds
spec:
  selector:
    matchLabels:
      app: max
  template:
    metadata:
      labels:
              app: max
    spec:
      containers:
      - name: max
        image: ubuntu
        stdin: true
        tty: true
