apiVersion: v1
kind: Service
metadata:      
  name: nginx-dns
  labels: 
    app: nginx-dns
spec:
  clusterIP: None      
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dns  
