apiVersion: v1
kind: Pod
metadata: 
  name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
  - name: redis
    image: redis
  - name: memcashed
    image: memcached
  - name: consul
    image: consul  
