apiVersion: v1
kind: Namespace
metadata:
  name: test


---
apiVersion: v1
kind: Pod
metadata:
  namespace: test     
  name: test
spec:
  containers:
  - name: test
    image: busybox
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
    args:
    - /bin/sh
    - -c
    - echo hello max; /bin/bash       

