apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    milan: champion      
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/app-data      
            
       
