apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    milan: champion      
spec:
  containers:
  - image: mysql
    name: max
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: password
    ports:
    - containerPort: 3306
      name: http
      protocol: TCP      
