apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: frontend      
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http
    volumeMounts:
    - name: app-data
      mountPath: /usr/share/nginx/html
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: app-data-claim      
